spring:
  application:
    name: "Quiz"
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb;MODE=MySQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=false
    username: sa
    password: password
    testOnBorrow: true
    testWhileIdle: true
  flyway:
    url: jdbc:h2:mem:mydb
    user: sa
    password: password
    locations: classpath:/db/migration
